; Aftermath Settings
; Created With RedEdit 98 Professional, Version 2.1.7.0
;
; Visit the RedEdit98 web site at, http://www.childs-play-software.com
; RedEdit 98 Professional is (C) 1997-2023 S.Childs, Childs Play Software.
; File Created :1/21/2024
; Compile Date/Time : 1/21/2024,11:33:00 PM
;
; Settings Author : NightFalcon101
; Settings Description : Mod created in RedEdit 98
; This file is the (C) of the author(s). If it is modified please credit them.
; Falcon'sModerateWarfare aftrmath.ini file.

[Aftermath]
MTankDistance=20
QuakeUnitDamage=45%
QuakeBuildingDamage=40%
QuakeInfantryDamage=0
QuakeDelay=120
CarrierLaunchDelay=30
ChronoTankDuration=2

; Phase Transporter
[STNK]
Prerequisite=weap,atek
Primary=APTusk
Strength=200
Armor=heavy
TechLevel=9 			; NightFalcon101 MODERATE_WARFARE Originally. TechLevel=-1
Sight=5
Speed=10
Owner=allies,soviet
Cost=800
Points=25
ROT=5
Tracked=yes
Passengers=1
Cloakable=yes
SelfHealing=no

; Carrier
[CARR]
Prerequisite=hpad,atek
Strength=350
Primary=AirAssault
Armor=heavy
TechLevel=9 			; NightFalcon101 MODERATE_WARFARE Originally. TechLevel=-1
Sight=6
Speed=6
Owner=allies,soviet
Cost=1200
Points=25
ROT=7
Passengers=5

; Chrono Tank
[CTNK]
Prerequisite=atek
Primary=APTusk
Strength=350
Armor=light
TechLevel=12
Sight=5
Speed=5
Owner=allies
Cost=2400
Points=25
ROT=5
Tracked=yes
HumanHealing=yes 		; NightFalcon101 MODERATE_WARFARE ADDED.

; Tesla Tank
[TTNK]
Prerequisite=tsla
Primary=TTankZap
Strength=110
Armor=light
TechLevel=8
Sight=7
Speed=8
Owner=soviet
Cost=1500
Points=30
ROT=5
Tracked=yes
Crewed=yes
NoMovingFire=yes

; Demolition Truck
[DTRK]
Prerequisite=mslo
Primary=Democharge
Strength=110
Armor=light
TechLevel=13
Sight=3
Speed=8
Owner=allies,soviet
Cost=2400
Points=5
ROT=5
Explodes=yes

; M.A.D. Tank
[QTNK]
Prerequisite=stek
Primary=none
Strength=300
Armor=heavy
TechLevel=10
Sight=6
Speed=3
Owner=soviet
Cost=2300
Points=60
ROT=5
Tracked=yes
Crewed=no

; Missile Submarine
[MSUB]
Prerequisite=stek
Primary=SubSCUD
Strength=150
Armor=light
TechLevel=9
Sight=6
Speed=5
Owner=soviet
Cost=1650
Points=45
ROT=7
Cloakable=yes
Inaccurate=no

; Shock Trooper
[SHOK]
Prerequisite=tsla
Primary=PortaTesla
Strength=80
Armor=none
TechLevel=7
Sight=4
Speed=3
Owner=soviet
Cost=900
Points=15
Explodes=no
NoMovingFire=yes
Crushable=no

; Field Mechanic
[MECH]
Prerequisite=fix
Primary=GoodWrench
Strength=60
Armor=none
TechLevel=7
Sight=3
Speed=4
Owner=allies
Cost=950
Points=15
Crushable=no 			; NightFalcon101 MODERATE_WARFARE ADDED.

; Aircraft Carrier Weapon
[AirAssault]
Damage=0
ROF=60
Range=127
Projectile=Invisible
Speed=100
Warhead=Super

; Portable Tesla Coil Weapon
[PortaTesla]
Damage=45
ROF=70
Range=3.5
Projectile=Invisible
Speed=100
Warhead=Super
Report=SHKTROP1
Charges=yes

; Tesla Tank Weapon
[TTankZap]
Damage=100
ROF=120
Range=7
Projectile=Invisible
Speed=100
Warhead=Super
Report=TESLA1
Charges=yes

; Mr. Goodwrench Mechanic's Healing Weapon
[GoodWrench]
Damage=-100
ROF=80
Range=1.83
Projectile=Invisible
Speed=100
Warhead=Mechanical
Report=FIXIT1

; Mechanical Warhead - Doesn't Affect Infantry (only for mechanic, not weapons)
[Mechanical]
Spread=0
Verses=100%,100%,100%,100%,100%
InfDeath=0

; Submarine's Scud Missile
[SubSCUD]
Damage=400
ROF=120
Range=14
Projectile=HeatSeeker
Speed=20
Warhead=HE
Report=MISSILE6
Burst=2

; Chrono Tank's Missile
[APTusk]
Damage=75
ROF=80
Range=5
Projectile=HeatSeeker
Speed=30
Warhead=AP
Report=MISSILE6
Burst=2

; Demolition Truck Charge
[Democharge]
Anim=none
Damage=500
Speed=100
Range=1.75
Projectile=Invisible
Warhead=Nuke
ROF=80

; This Needs To Be Re-Set From Its Modified mplayer.ini Values
[TurretGun]
Burst=1
Damage=40
ROF=50
Range=6
Projectile=Cannon
Speed=40
Warhead=AP
Report=TURRET1
Anim=GUNFIRE

; Transport
[LST]
Strength=350
Armor=heavy
TechLevel=3
Sight=6
Speed=14
Owner=allies,soviet
Cost=700
Points=25
ROT=10
Passengers=5
SelfHealing=no

; Fake
[FACF]
Image=FACT
Owner=allies
TechLevel=-1 			;Falcon Original. TechLevel=1
Strength=30
Cost=50
Sight=4
Power=-2
Points=15
Bib=yes
Capturable=true
BaseNormal=no
Armor=none

; Fake
[WEAF]
Prerequisite=proc
Image=WEAP
Owner=allies
TechLevel=-1 			;Falcon Original. TechLevel=3
Cost=50
Strength=30
Sight=4
Points=15
Power=-2
Bib=yes
Capturable=true
BaseNormal=no
Armor=none

; Fake
[DOMF]
Prerequisite=proc
Image=DOME
Strength=30
Sight=4
TechLevel=-1 			;Falcon Original. TechLevel=3
Cost=50
Owner=allies
Power=-2
Points=15
Bib=yes
Capturable=true
BaseNormal=no
Armor=none

; Mammoth Tank
[4TNK]
Prerequisite=weap,stek
Primary=120mm
Secondary=MammothTusk
Strength=600
Armor=heavy
TechLevel=10
Sight=6
Speed=4
Owner=soviet
Cost=1700
Points=60
ROT=5
Tracked=yes
SelfHealing=yes
Crewed=yes
Explodes=no
HumanHealing=yes		; NightFalcon101 MODERATE_WARFARE ADDED.

; Civilian
[C2]
Primary=none
Image=C1
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes

; Civilian
[C3]
Infiltrate=no
Primary=none
Image=C2
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes

; Civilian
[C4]
Primary=none
Infiltrate=no
Image=C2
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes

; Civilian
[C5]
Infiltrate=no
Image=C2
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes

; Civilian
[C6]
Image=C1
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes
Infiltrate=no
Primary=none

; Civilian
[C9]
Image=C1
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Fraidycat=yes
Primary=none

; Depth Charge Catapult
[Catapult]
Animates=no
High=yes
Arcing=yes
Inaccurate=yes
Image=BOMB
Frames=8
ASW=yes
AG=no
Translucent=yes

; Auxiliary Decorative Building
[MISS]
Strength=400
Points=5
Armor=wood
Bib=yes
Capturable=true
Owner=allies,soviet

; Bio-Research Laboratory
[BIO]
Strength=600
Armor=wood
TechLevel=-1
Sight=4
Owner=
Cost=
Points=30
Power=-40
Bib=yes
Crewed=yes
Capturable=false

; Field Marshal
[GNRL]
Primary=Pistol
Strength=80
Armor=none
TechLevel=-1
Sight=3
Speed=5
Owner=allies,soviet
Cost=0
Points=15
Infiltrate=yes
Secondary=none
C4=no
DoubleOwned=no
Burst=1

; Attack Dog
[DOG]
Prerequisite=kenn
Primary=DogJaw
Strength=12
;Strength=5
Armor=none
TechLevel=3
Sight=5
Speed=4
Owner=soviet
Cost=200
Points=5
IsCanine=yes
GuardRange=7
Selfhealing=no

; Special Agent
[CHAN]
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Infiltrate=no

; Rocket Soldier
[E3]
Primary=RedEye
Secondary=Dragon
Strength=45
Armor=none
TechLevel=2
Sight=4
Speed=3
Owner=allies
Cost=300
Points=10
DoubleOwned=yes
Infiltrate=no

; Artillery Cannon
[155mm]
Damage=150
ROF=65
Range=6
Projectile=Ballistic
Speed=12
Warhead=HE
Report=TANK5
Anim=GUNFIRE
Burst=1

; Special Agent
[DELPHI]
Infiltrate=no
Primary=Pistol
Strength=25
Armor=none
TechLevel=-1
Sight=2
Speed=5
Owner=allies,soviet
Cost=10
Points=1
Ammo=10